# Generated by Django 4.2.11 on 2024-04-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finches',
            new_name='Finch',
        ),
    ]
