# Generated by Django 4.2.11 on 2024-04-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_finch_sex_feeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='sighting date')),
                ('where', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('F', 'Flying'), ('S', 'Sleeping'), ('D', 'Drinking water'), ('E', 'Eating'), ('M', 'Mating')], max_length=1)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.finch')),
            ],
        ),
    ]
